import 'server-only';

import sharp from 'sharp';

import {
  CodexUnavailableError,
  isCodexAvailable,
  runCodex,
  type CodexImageInput,
} from './codexRunner';

// ─────────────────────────────────────────────────────────────────────────────
// Man report AI routing. Men's Blueprints are generated by the operator on
// their own Mac, so every Man text and image call goes to ChatGPT through the
// signed-in Codex CLI first. Gemini is the fallback only:
//   - on Vercel or any machine without Codex (production keeps working);
//   - when one Codex call fails (that call is retried on Gemini);
//   - while the ChatGPT usage window is exhausted (Codex is skipped until the
//     cooldown ends, so a batch doesn't burn minutes timing out).
//
// MAN_AI_PROVIDER=gemini forces Gemini everywhere (e.g. to compare outputs).
// Other products (women, Globe, Edit, WhatsApp) never import this module.
// ─────────────────────────────────────────────────────────────────────────────

const TEXT_TIMEOUT_MS = 12 * 60_000;   // Section 4 writes 20 outfits in one call
const IMAGE_TIMEOUT_MS = 4 * 60_000;   // a Codex image takes ~50s; leave room for queueing
const GEMINI_SOFT_DEADLINE_MS = 260_000;
const CODEX_SOFT_DEADLINE_MS = 25 * 60_000;

let codexPausedUntil = 0;
let codexPauseReason = '';

export type ManAiEngine = 'codex' | 'gemini';

export function manAiEngine(): ManAiEngine {
  if (process.env.MAN_AI_PROVIDER?.trim().toLowerCase() === 'gemini') return 'gemini';
  if (!isCodexAvailable()) return 'gemini';
  if (Date.now() < codexPausedUntil) return 'gemini';
  return 'codex';
}

export function manAiStatus(): { engine: ManAiEngine; note: string | null } {
  const engine = manAiEngine();
  if (engine === 'codex') return { engine, note: null };
  if (Date.now() < codexPausedUntil) {
    const minutes = Math.ceil((codexPausedUntil - Date.now()) / 60_000);
    return { engine, note: `ChatGPT paused for ${minutes} min: ${codexPauseReason}` };
  }
  return { engine, note: null };
}

/**
 * Image pipelines stop starting new images at this point and let the admin
 * resume. Gemini on Vercel must finish inside the 300s function cap; a local
 * Codex run has no cap and images are ~50s each, so one pass can finish a report.
 */
export function manImageSoftDeadlineMs(): number {
  return Date.now() + (manAiEngine() === 'codex' ? CODEX_SOFT_DEADLINE_MS : GEMINI_SOFT_DEADLINE_MS);
}

function pauseCodex(err: CodexUnavailableError) {
  codexPausedUntil = Date.now() + err.retryAfterMs;
  codexPauseReason = err.message;
  console.error(`[manAi] Codex paused for ${Math.round(err.retryAfterMs / 60_000)} min, using Gemini: ${err.message}`);
}

async function withGeminiFallback<T>(
  label: string,
  viaCodex: () => Promise<T>,
  viaGemini: () => Promise<T>,
): Promise<T> {
  if (manAiEngine() !== 'codex') return viaGemini();
  try {
    return await viaCodex();
  } catch (err) {
    if (err instanceof CodexUnavailableError) pauseCodex(err);
    const message = err instanceof Error ? err.message : String(err);
    console.error(`[manAi] ${label} FAILED on Codex, falling back to Gemini: ${message.slice(0, 400)}`);
    return viaGemini();
  }
}

const TEXT_PREAMBLE = `You are being called as a plain text-generation endpoint inside an automated pipeline.
Do not run shell commands, do not read or write files, do not ask questions, and do not describe what you are doing.
Reply with the final answer only, exactly in the format the instructions below ask for.`;

export async function manGenerateText(
  input: { label: string; prompt: string; images?: CodexImageInput[] },
  viaGemini: () => Promise<string>,
): Promise<string> {
  return withGeminiFallback(input.label, async () => {
    const imageNote = input.images?.length
      ? `\n${input.images.length === 1 ? 'One image is' : `${input.images.length} images are`} attached, in the order the instructions refer to them.`
      : '';
    const result = await runCodex({
      prompt: `${TEXT_PREAMBLE}${imageNote}\n\n---\n\n${input.prompt}`,
      images: input.images,
      output: 'text',
      timeoutMs: TEXT_TIMEOUT_MS,
      label: input.label,
    });
    console.log(`[manAi] ${input.label} via Codex in ${(result.durationMs / 1000).toFixed(1)}s`);
    return result.text;
  }, viaGemini);
}

/** Returns base64 JPEG data, like the Gemini image path it replaces (storage uploads label it image/jpeg). */
export async function manGenerateImage(
  input: { label: string; prompt: string; images: CodexImageInput[] },
  viaGemini: () => Promise<string>,
): Promise<string> {
  return withGeminiFallback(input.label, async () => {
    const roles = input.images.length > 1
      ? `Image 1 is the primary source photo. Image 2 is a supporting reference. The instructions below refer to them in that order.`
      : `The attached image is the source photo the instructions below refer to.`;
    const result = await runCodex({
      prompt: `You are being called as an image-generation endpoint inside an automated pipeline.
Immediately call your built-in image generation tool exactly once, editing from the attached image(s).
Pass the brief below to the tool as faithfully as possible: keep every constraint, colour, garment and identity rule. Do not shorten it into a summary.
Do not run shell commands and do not read or write files. If the image is portrait-oriented, generate a portrait image.
After the image is generated, reply with the single word DONE.

${roles}

BRIEF:
${input.prompt}`,
      images: input.images,
      output: 'image',
      timeoutMs: IMAGE_TIMEOUT_MS,
      label: input.label,
    });
    console.log(`[manAi] ${input.label} image via Codex in ${(result.durationMs / 1000).toFixed(1)}s`);
    const jpeg = await sharp(Buffer.from(result.image!.data, 'base64'), { failOn: 'none' })
      .jpeg({ quality: 92, mozjpeg: true })
      .toBuffer();
    return jpeg.toString('base64');
  }, viaGemini);
}
