// Display labels for the self-serve intake's piece-preference option ids.
export const PIECE_PREFERENCE_LABELS: Record<string, string> = {
  relaxed_oversized: 'relaxed oversized tops',
  fitted_tuck_in: 'fitted tucked-in tops',
  structured_button_front: 'structured button-front tops',
  draped_wrap: 'draped or wrap tops',
  detailed_collar: 'detailed collar tops',
  clean_minimal: 'clean minimal tops',
  wide_leg_trouser: 'wide-leg trousers',
  straight_cigarette: 'straight cigarette bottoms',
  tailored_midi_skirt: 'tailored midi skirts',
  wrap_skirt: 'wrap skirts',
  straight_jeans: 'fitted straight jeans',
  bootcut: 'flared or bootcut bottoms',
  structured_blazer: 'structured blazers',
  longline_coat: 'longline coats',
  denim_jacket: 'denim jackets',
  moto_jacket: 'leather or moto jackets',
  knit_cardigan: 'knit cardigans',
  linen_blazer: 'unstructured linen blazers',
  structured_bag: 'structured bags',
  soft_tote: 'soft totes',
  minimal_jewellery: 'minimal jewellery',
  statement_jewellery: 'statement jewellery',
  classic_shoe: 'classic shoes',
  modern_shoe: 'modern shoes',
};
