import { MetadataRoute } from "next";

const BASE = "https://www.iconik.pro";
const NOW = new Date("2026-04-16T00:00:00.000Z").toISOString();

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    // ─── Core pages ─────────────────────────────────────────────
    { url: `${BASE}/`, lastModified: NOW, changeFrequency: "weekly", priority: 1.0 },
    { url: `${BASE}/about`, lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/contact`, lastModified: NOW, changeFrequency: "monthly", priority: 0.6 },
    { url: `${BASE}/how-it-works`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/pricing`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/results`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/what-is-iconik`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/who-is-iconik-for`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/iconik-methodology`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/globe`, lastModified: NOW, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/uae`, lastModified: NOW, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/au`, lastModified: NOW, changeFrequency: "weekly", priority: 0.9 },
    { url: `${BASE}/us`, lastModified: NOW, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/man`, lastModified: NOW, changeFrequency: "weekly", priority: 0.8 },
    { url: `${BASE}/iconik-club/join`, lastModified: NOW, changeFrequency: "monthly", priority: 0.6 },

    // ─── Variant landing pages ───────────────────────────────────
    { url: `${BASE}/arms`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/tummy`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/plus-size`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/modest`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/monthly`, lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/monthly/indian`, lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },

    // ─── FAQ pillar + spokes ─────────────────────────────────────
    { url: `${BASE}/faq`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/faq/warm-or-cool-undertone`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/colour-analysis-at-home`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/colour-analysis-dark-skin`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/what-is-seasonal-colour-analysis`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/what-is-iconik-style-blueprint`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/body-shape-vs-body-type`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/most-common-body-type-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/does-black-make-you-look-slimmer`, lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/faq/neckline-round-face`, lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/faq/capsule-wardrobe-how-many-outfits`, lastModified: NOW, changeFrequency: "monthly", priority: 0.7 },
    { url: `${BASE}/faq/how-much-does-personal-stylist-cost-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/how-to-build-capsule-wardrobe-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/what-colours-make-you-look-slimmer-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/neckline-guide-face-shape-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/faq/how-to-dress-for-job-interview-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },

    // ─── Body type styling pillar + spokes ───────────────────────
    { url: `${BASE}/body-type-styling`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/body-shape-consultation-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/apple`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/pear`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/rectangle`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/plus-size`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/hourglass`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/apple-body-shape-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/pear-body-shape-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/rectangle-body-shape-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/plus-size-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/heavy-arms-styling`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/how-to-dress-tummy`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/short-torso-styling`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/how-to-look-taller-clothing`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/inverted-triangle`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/hourglass-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/petite-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/body-type-styling/rectangle-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },

    // ─── Colour analysis pillar + spokes ─────────────────────────
    { url: `${BASE}/colour-analysis`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/colour-analysis-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/how-to-find-undertone`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/warm-cool-neutral-undertone-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/warm-undertone`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/cool-undertone`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/neutral-undertone`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/indian-skin-tones`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/best-colours-dusky-skin`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/best-colours-wheatish-skin-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/best-colours-fair-skin-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/saree-colours-by-undertone`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/seasonal-colour-analysis-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/olive-skin-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/colour-analysis-for-indian-weddings`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/colour-analysis/dark-skin-colour-guide-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },

    // ─── Methodology (AEO entity pages) ──────────────────────────
    { url: `${BASE}/methodology`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/methodology/chromatic-harmony-mapping`, lastModified: NOW, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/methodology/geometric-silhouette-profiling`, lastModified: NOW, changeFrequency: "yearly", priority: 0.9 },
    { url: `${BASE}/methodology/facial-architecture-analysis`, lastModified: NOW, changeFrequency: "yearly", priority: 0.9 },

    // ─── Style guides cluster ─────────────────────────────────────
    { url: `${BASE}/style-guides`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/style-guides/capsule-wardrobe-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/office-wear-indian-women`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/saree-draping-body-type`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/salwar-kameez-body-type`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/kurti-length-guide`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/indian-wedding-guest-outfit`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/diwali-outfit-body-type`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/postpartum-fashion-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/dressing-after-weight-gain`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/fashion-40s-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/style-guides/modest-professional-fashion-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/wardrobe-audit-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/capsule-wardrobe-service-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },

    // ─── VS / Comparison pages ───────────────────────────────────
    { url: `${BASE}/vs`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/vs/online-vs-inperson-styling`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/vs/iconik-vs-styling-apps`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/vs/style-blueprint-vs-quiz`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/vs/chromatic-harmony-mapping-vs-seasonal-colour-analysis`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/personal-shopper-vs-personal-stylist-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },

    // ─── City landing pages ──────────────────────────────────────
    { url: `${BASE}/personal-stylist-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/online-personal-stylist-india`, lastModified: NOW, changeFrequency: "monthly", priority: 0.9 },
    { url: `${BASE}/personal-stylist-mumbai`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-bangalore`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-delhi`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-hyderabad`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-chennai`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-pune`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-kolkata`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-ahmedabad`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-kochi`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-jaipur`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-surat`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-nagpur`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-indore`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-lucknow`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-chandigarh`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-visakhapatnam`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-coimbatore`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-bhopal`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-patna`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-thiruvananthapuram`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-vadodara`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },
    { url: `${BASE}/personal-stylist-mysuru`, lastModified: NOW, changeFrequency: "monthly", priority: 0.8 },

    // ─── Blog / AEO definition posts ─────────────────────────────
    { url: `${BASE}/blog`, lastModified: NOW, changeFrequency: "weekly", priority: 0.7 },
    { url: `${BASE}/blog/what-is-geometric-silhouette-profiling`, lastModified: NOW, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/blog/what-is-chromatic-harmony-mapping`, lastModified: NOW, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/blog/what-is-facial-architecture-analysis`, lastModified: NOW, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/blog/is-personal-stylist-worth-it-india`, lastModified: NOW, changeFrequency: "yearly", priority: 0.8 },
    { url: `${BASE}/glossary/personal-styling-terms-india`, lastModified: NOW, changeFrequency: "yearly", priority: 0.7 },

    // ─── Legal ───────────────────────────────────────────────────
    { url: `${BASE}/terms`, lastModified: NOW, changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE}/privacy-policy`, lastModified: NOW, changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE}/refund-policy`, lastModified: NOW, changeFrequency: "yearly", priority: 0.3 },
    { url: `${BASE}/shipping`, lastModified: NOW, changeFrequency: "yearly", priority: 0.3 },
  ];
}
