-- Jazz pilot workspace for India consultation Blueprint production.
-- Existing admin/customer Blueprint flows remain compatible.

ALTER TABLE public.stylists
  ADD COLUMN IF NOT EXISTS slug text,
  ADD COLUMN IF NOT EXISTS workspace_enabled boolean NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS is_active boolean NOT NULL DEFAULT true;

UPDATE public.stylists
SET slug = trim(both '-' from regexp_replace(lower(name), '[^a-z0-9]+', '-', 'g'))
WHERE slug IS NULL OR btrim(slug) = '';

UPDATE public.stylists
SET workspace_enabled = (lower(name) = 'jazz');

CREATE UNIQUE INDEX IF NOT EXISTS stylists_slug_unique_idx
  ON public.stylists(slug)
  WHERE slug IS NOT NULL;

CREATE TABLE IF NOT EXISTS public.stylist_sessions (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  stylist_id uuid NOT NULL REFERENCES public.stylists(id) ON DELETE CASCADE,
  token_hash text NOT NULL UNIQUE,
  ip_hash text,
  user_agent text,
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS stylist_sessions_active_idx
  ON public.stylist_sessions(token_hash, expires_at)
  WHERE revoked_at IS NULL;

CREATE TABLE IF NOT EXISTS public.stylist_login_attempts (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  stylist_id uuid REFERENCES public.stylists(id) ON DELETE CASCADE,
  ip_hash text NOT NULL,
  succeeded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS stylist_login_attempts_guard_idx
  ON public.stylist_login_attempts(stylist_id, ip_hash, created_at DESC);

ALTER TABLE public.stylist_intake_responses
  ADD COLUMN IF NOT EXISTS consultation_id uuid REFERENCES public.consultations(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS assigned_stylist_id uuid REFERENCES public.stylists(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS source_snapshot jsonb,
  ADD COLUMN IF NOT EXISTS source_photo_paths jsonb,
  ADD COLUMN IF NOT EXISTS workspace_overrides jsonb NOT NULL DEFAULT '{}'::jsonb;

ALTER TABLE public.stylist_intake_responses
  DROP CONSTRAINT IF EXISTS stylist_intake_responses_intake_source_check;

ALTER TABLE public.stylist_intake_responses
  ADD CONSTRAINT stylist_intake_responses_intake_source_check
  CHECK (intake_source = ANY (ARRAY[
    'customer_form'::text,
    'manual_admin'::text,
    'india_consultation'::text
  ]));

CREATE UNIQUE INDEX IF NOT EXISTS stylist_intake_consultation_unique_idx
  ON public.stylist_intake_responses(consultation_id)
  WHERE consultation_id IS NOT NULL;

CREATE INDEX IF NOT EXISTS stylist_intake_assignee_idx
  ON public.stylist_intake_responses(assigned_stylist_id, created_at DESC);

ALTER TABLE public.stylist_blueprint_reports
  ADD COLUMN IF NOT EXISTS created_by_stylist_id uuid REFERENCES public.stylists(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS published_at timestamptz,
  ADD COLUMN IF NOT EXISTS delivered_at timestamptz,
  ADD COLUMN IF NOT EXISTS revision integer NOT NULL DEFAULT 1;

ALTER TABLE public.stylist_blueprint_reports
  DROP CONSTRAINT IF EXISTS stylist_blueprint_reports_status_check;

ALTER TABLE public.stylist_blueprint_reports
  ADD CONSTRAINT stylist_blueprint_reports_status_check
  CHECK (status = ANY (ARRAY[
    'pending'::text,
    'generating'::text,
    'draft_ready'::text,
    'in_review'::text,
    'approved'::text,
    'sent'::text,
    'delivered'::text,
    'error'::text
  ]));

-- Prevent two refreshes/double-clicks from creating parallel active reports for
-- one consultation intake. Delivered/error reports remain available as history.
CREATE UNIQUE INDEX IF NOT EXISTS stylist_blueprint_active_consultation_unique_idx
  ON public.stylist_blueprint_reports(submission_id)
  WHERE created_by_stylist_id IS NOT NULL
    AND status NOT IN ('delivered', 'sent', 'error');

CREATE TABLE IF NOT EXISTS public.stylist_report_jobs (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  report_id uuid NOT NULL REFERENCES public.stylist_blueprint_reports(id) ON DELETE CASCADE,
  consultation_id uuid REFERENCES public.consultations(id) ON DELETE SET NULL,
  stylist_id uuid REFERENCES public.stylists(id) ON DELETE SET NULL,
  job_type text NOT NULL DEFAULT 'full_report',
  target text NOT NULL DEFAULT 'all',
  status text NOT NULL DEFAULT 'queued' CHECK (status IN (
    'queued', 'running', 'retry_wait', 'completed', 'failed', 'cancelled'
  )),
  attempt_count integer NOT NULL DEFAULT 0,
  max_attempts integer NOT NULL DEFAULT 4,
  next_run_at timestamptz NOT NULL DEFAULT now(),
  locked_at timestamptz,
  heartbeat_at timestamptz,
  last_error text,
  intake_snapshot jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE public.stylist_report_jobs
  ADD COLUMN IF NOT EXISTS intake_snapshot jsonb,
  ALTER COLUMN max_attempts SET DEFAULT 4;

CREATE UNIQUE INDEX IF NOT EXISTS stylist_report_jobs_active_unique_idx
  ON public.stylist_report_jobs(report_id, job_type, target)
  WHERE status IN ('queued', 'running', 'retry_wait');

CREATE INDEX IF NOT EXISTS stylist_report_jobs_claim_idx
  ON public.stylist_report_jobs(status, next_run_at, created_at);

CREATE TABLE IF NOT EXISTS public.stylist_report_activity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  report_id uuid REFERENCES public.stylist_blueprint_reports(id) ON DELETE CASCADE,
  consultation_id uuid REFERENCES public.consultations(id) ON DELETE SET NULL,
  stylist_id uuid REFERENCES public.stylists(id) ON DELETE SET NULL,
  action text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS stylist_report_activity_report_idx
  ON public.stylist_report_activity(report_id, created_at DESC);

CREATE INDEX IF NOT EXISTS consultations_stylist_queue_idx
  ON public.consultations(stylist_id, status, report_due_at, updated_at DESC);

ALTER TABLE public.stylist_sessions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stylist_login_attempts ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stylist_report_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.stylist_report_activity ENABLE ROW LEVEL SECURITY;

-- Atomic job claim used by the server-only worker. Service-role callers bypass RLS.
CREATE OR REPLACE FUNCTION public.claim_stylist_report_jobs(_limit integer DEFAULT 2)
RETURNS SETOF public.stylist_report_jobs
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  available_slots integer;
BEGIN
  -- Serialize claimers so overlapping cron invocations cannot exceed the
  -- workspace-wide two-report concurrency cap.
  PERFORM pg_advisory_xact_lock(hashtext('stylist_report_jobs_global_claim'));

  SELECT GREATEST(0, 2 - count(*))::integer
  INTO available_slots
  FROM public.stylist_report_jobs
  WHERE status = 'running'
    AND COALESCE(heartbeat_at, locked_at) >= now() - interval '10 minutes';

  RETURN QUERY
  WITH candidates AS (
    SELECT id
    FROM public.stylist_report_jobs
    WHERE (
      (status IN ('queued', 'retry_wait') AND next_run_at <= now())
      OR (status = 'running' AND COALESCE(heartbeat_at, locked_at) < now() - interval '10 minutes')
    )
    ORDER BY created_at
    FOR UPDATE SKIP LOCKED
    LIMIT LEAST(GREATEST(_limit, 1), available_slots)
  )
  UPDATE public.stylist_report_jobs jobs
  SET status = 'running',
      attempt_count = jobs.attempt_count + 1,
      locked_at = now(),
      heartbeat_at = now(),
      updated_at = now()
  FROM candidates
  WHERE jobs.id = candidates.id
  RETURNING jobs.*;
END;
$$;

REVOKE ALL ON FUNCTION public.claim_stylist_report_jobs(integer) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.claim_stylist_report_jobs(integer) TO service_role;
