'use client';

import { useCallback, useEffect, useState } from 'react';
import Image from 'next/image';
import Link from 'next/link';
import { ArrowLeft, CheckCircle2, RefreshCw, Save } from 'lucide-react';
import type { InstantReportV1 } from '@/lib/styleScan';

interface AdminReport { id: string; status: string; report_data: InstantReportV1; imageUrls: Array<string | null>; sla_due_at: string; stylist_orders?: { customer_name?: string; customer_email?: string }; instant_report_intakes?: { hard_nos?: string; final_note?: string } }
export default function InstantReportAdminEditor({ reportId }: { reportId: string }) {
  const [report, setReport] = useState<AdminReport | null>(null); const [busy, setBusy] = useState(''); const [message, setMessage] = useState('');
  const load = useCallback(async () => { const response = await fetch(`/api/instant-report/admin/${reportId}`, { cache: 'no-store' }); if (response.status === 401) { window.location.assign('/stylist/admin/login'); return; } const data = await response.json(); if (!response.ok) { setMessage(data.error || 'Could not load report.'); return; } setReport(data.report); }, [reportId]);
  useEffect(() => { void load(); }, [load]);
  const patchOutfit = (index: number, key: keyof InstantReportV1['outfits'][number], value: string) => setReport(current => current ? { ...current, report_data: { ...current.report_data, outfits: current.report_data.outfits.map((outfit, i) => i === index ? { ...outfit, [key]: value } : outfit) } } : current);
  const patchText = (key: 'snapshot' | 'chromaticProfile' | 'outfitSystem', value: string) => setReport(current => current ? { ...current, report_data: { ...current.report_data, [key]: value } } : current);
  const patchList = (key: 'proportionRules' | 'shoppingRules' | 'checklist', value: string) => setReport(current => current ? { ...current, report_data: { ...current.report_data, [key]: value.split('\n').map(item => item.trim()).filter(Boolean) } } : current);
  const save = async () => { if (!report) return; setBusy('save'); const response = await fetch(`/api/instant-report/admin/${reportId}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ reportData: report.report_data }) }); const data = await response.json(); setMessage(response.ok ? 'Saved.' : data.error || 'Save failed.'); setBusy(''); };
  const approve = async () => { setBusy('approve'); const response = await fetch(`/api/instant-report/admin/${reportId}/approve`, { method: 'POST' }); const data = await response.json(); setMessage(response.ok ? 'Approved and published.' : data.error || 'Approval failed.'); setBusy(''); if (response.ok) void load(); };
  const regenerate = async (index: number) => { setBusy(`image-${index}`); const response = await fetch(`/api/instant-report/admin/${reportId}/regenerate-image`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ index }) }); const data = await response.json(); setMessage(response.ok ? `Outfit ${index + 1} image regenerated.` : data.error || 'Regeneration failed.'); setBusy(''); if (response.ok) void load(); };
  if (!report?.report_data) return <div className="p-10 text-center text-sm text-[#2C2622]/45">{message || 'Loading report…'}</div>;
  return <div className="mx-auto max-w-5xl"><div className="mb-6 flex flex-wrap items-center justify-between gap-4"><div><Link href="/stylist/admin/instant" className="mb-3 flex items-center gap-2 text-xs text-[#2C2622]/45"><ArrowLeft className="h-3.5 w-3.5" /> Instant reports</Link><h1 className="iconik-display text-3xl">{report.stylist_orders?.customer_name || report.stylist_orders?.customer_email || 'Instant Report'}</h1><p className="mt-2 text-xs text-[#2C2622]/45">Status: {report.status.replace(/_/g,' ')} · SLA {new Date(report.sla_due_at).toLocaleString('en-IN')}</p></div><div className="flex gap-2"><button onClick={() => void save()} disabled={Boolean(busy)} className="flex items-center gap-2 rounded-xl border border-[#2C2622]/12 bg-white px-4 py-3 text-xs"><Save className="h-4 w-4" /> Save edits</button><button onClick={() => void approve()} disabled={Boolean(busy) || report.status !== 'review_required'} className="flex items-center gap-2 rounded-xl bg-[#2C2622] px-4 py-3 text-xs text-white disabled:opacity-35"><CheckCircle2 className="h-4 w-4" /> Approve & publish</button></div></div>
    {message && <div className="mb-5 rounded-xl bg-[#EDE5D2] p-3 text-xs">{message}</div>}
    <section className="mb-6 rounded-2xl border border-[#2C2622]/10 bg-[#EDE5D2] p-5"><div className="iconik-micro mb-3 text-[#2C2622]/40">CUSTOMER CONSTRAINTS</div><p className="text-xs leading-6 text-[#2C2622]/65"><strong>Hard no’s:</strong> {report.instant_report_intakes?.hard_nos || 'None supplied'}<br/><strong>Final note:</strong> {report.instant_report_intakes?.final_note || 'None supplied'}</p></section>
    <section className="mb-6 rounded-2xl border border-[#2C2622]/10 bg-white p-5"><div className="iconik-micro mb-4 text-[#B68C52]">ANALYSIS & SYSTEM PAGES</div><div className="grid gap-4 md:grid-cols-2">{([
      ['snapshot','Style snapshot',report.report_data.snapshot],
      ['chromaticProfile','Chromatic profile',report.report_data.chromaticProfile],
      ['outfitSystem','Outfit system',report.report_data.outfitSystem],
    ] as const).map(([key,label,value]) => <label key={key} className="text-[10px] uppercase tracking-wider text-[#2C2622]/45">{label}<textarea value={value} onChange={event => patchText(key,event.target.value)} rows={4} className="mt-1 w-full rounded-xl border border-[#2C2622]/12 px-3 py-2 text-xs normal-case tracking-normal text-[#2C2622] outline-none" /></label>)}{([
      ['proportionRules','Proportion rules',report.report_data.proportionRules],
      ['shoppingRules','Shopping rules',report.report_data.shoppingRules],
      ['checklist','Final checklist',report.report_data.checklist],
    ] as const).map(([key,label,value]) => <label key={key} className="text-[10px] uppercase tracking-wider text-[#2C2622]/45">{label}<textarea value={value.join('\n')} onChange={event => patchList(key,event.target.value)} rows={6} className="mt-1 w-full rounded-xl border border-[#2C2622]/12 px-3 py-2 text-xs normal-case tracking-normal text-[#2C2622] outline-none" /></label>)}</div></section>
    <div className="space-y-5">{report.report_data.outfits.map((outfit, index) => <section key={outfit.number} className="grid gap-5 rounded-2xl border border-[#2C2622]/10 bg-white p-5 md:grid-cols-[240px_1fr]">{report.imageUrls[index] ? <div><div className="relative aspect-[2/3] overflow-hidden rounded-xl bg-[#EDE5D2]"><Image src={report.imageUrls[index]!} alt={outfit.title} fill unoptimized className="object-cover" /></div><button onClick={() => void regenerate(index)} disabled={Boolean(busy)} className="mt-3 flex w-full items-center justify-center gap-2 rounded-xl border border-[#2C2622]/10 py-2.5 text-xs"><RefreshCw className="h-3.5 w-3.5" />{busy === `image-${index}` ? 'Regenerating…' : 'Regenerate image'}</button></div> : <div className="rounded-xl bg-[#EDE5D2] p-5 text-xs">Image missing</div>}<div><div className="iconik-micro mb-4 text-[#B68C52]">OUTFIT {String(index + 1).padStart(2,'0')}</div>{(['title','context','formula','silhouetteRationale','colourRationale','coverageNotes'] as const).map(key => <label key={key} className="mb-3 block text-[10px] uppercase tracking-wider text-[#2C2622]/45">{key.replace(/([A-Z])/g,' $1')}<textarea value={String(outfit[key])} onChange={event => patchOutfit(index, key, event.target.value)} rows={key === 'formula' ? 3 : 2} className="mt-1 w-full resize-y rounded-xl border border-[#2C2622]/12 px-3 py-2 text-xs normal-case tracking-normal text-[#2C2622] outline-none" /></label>)}</div></section>)}</div>
  </div>;
}
